import { createStitches } from '@stitches/react';

export const { styled, css, globalCss, theme } = createStitches({
  theme: {
    colors: {
      background: '#faf9f7',
      panel: '#ffffff',
      surface: '#f4f4f2',
      surfaceSoft: '#eeeeec',
      surfaceStrong: '#e8e8e6',
      text: '#1a1c1b',
      mutedText: '#5f6764',
      subtleText: '#717976',
      primary: '#01261f',
      primarySoft: '#c5eadf',
      primaryPanel: '#1a3c34',
      secondary: '#3a675a',
      secondarySoft: '#bceddd',
      accent: '#623d36',
      accentSoft: '#ffdad3',
      border: '#c1c8c4',
      borderSoft: '#e3e2e1',
      success: '#275d46',
      successSoft: '#dff4ea',
      warning: '#7b5a19',
      warningSoft: '#f6ead0',
      danger: '#ba1a1a',
      dangerSoft: '#ffdad6',
      shadowColor: 'rgba(26, 28, 27, 0.08)',
    },
    fonts: {
      body: '"Manrope", "Pretendard", "Apple SD Gothic Neo", "Noto Sans KR", sans-serif',
      heading: '"Newsreader", "Noto Serif KR", "Iowan Old Style", serif',
      mono: '"SFMono-Regular", Consolas, monospace',
    },
    radii: {
      sm: '8px',
      md: '12px',
      lg: '18px',
      xl: '24px',
      pill: '9999px',
    },
    space: {
      1: '4px',
      2: '8px',
      3: '12px',
      4: '16px',
      5: '20px',
      6: '24px',
      7: '32px',
      8: '40px',
      9: '56px',
    },
    fontSizes: {
      1: '12px',
      2: '13px',
      3: '16px',
      4: '18px',
      5: '28px',
      6: '40px',
    },
    shadows: {
      card: '0 10px 28px rgba(26, 28, 27, 0.05)',
      soft: '0 4px 14px rgba(26, 28, 27, 0.04)',
      focus: '0 0 0 3px rgba(58, 103, 90, 0.18)',
    },
  },
  media: {
    sm: '(min-width: 640px)',
    md: '(min-width: 768px)',
  },
});
